# Generated by Django 4.2.3 on 2023-07-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OKDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(default=None)),
                ('registrar', models.TextField(default=None, null=True)),
                ('server', models.TextField(default=None, null=True)),
                ('urlscan', models.TextField(default=None, null=True)),
                ('system', models.TextField(default=None, null=True)),
                ('system_owner', models.TextField(default=None, null=True)),
                ('comments', models.TextField(default=None, null=True)),
                ('vulnerabilities', models.TextField(default=None, null=True)),
                ('changes_since_last', models.TextField(default=None, null=True)),
            ],
        ),
    ]
