# Generated by Django 4.2.3 on 2023-07-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nessus', '0002_okdomains_screenshot_okdomains_tlsissuer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okdomains',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='okdomains',
            name='tlsissuer',
        ),
        migrations.RemoveField(
            model_name='okdomains',
            name='url',
        ),
    ]
