# Generated by Django 4.2.3 on 2023-08-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nessus', '0004_okdomains_nmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='okdomains',
            name='ip_data',
            field=models.TextField(default=None, null=True),
        ),
    ]
