# Generated by Django 4.2.3 on 2023-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nessus', '0006_okdomains_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='okdomains',
            name='http_code',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='okdomains',
            name='http_redirect',
            field=models.TextField(default=None, null=True),
        ),
    ]
